### ISSUE TITLE
Unable to generate pydantic-core schema for <class 'MBDynLib.Position'>

### ISSUE THREAD

**Issue by Shimul-Baidya** [Shimul-Baidya/MBDyn#8]
[Related commit](https://github.com/Shimul-Baidya/MBDyn/commit/af5d457d852c5a02871a56c515c13d13eb9faff8)

After rewriting `StructuralNode` with `MBEntity`, when I tried to run tests I ran into this error.
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/lib/python3.10/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.10/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/usr/lib/python3.10/unittest/main.py", line 158, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
  File "/usr/lib/python3.10/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.10/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.10/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/shimul/Downloads/MyGitHub/MBDyn/contrib/PythonPreprocessor/test_MBDynLib.py", line 4, in <module>
    import MBDynLib as l
  File "/home/shimul/Downloads/MyGitHub/MBDyn/contrib/PythonPreprocessor/MBDynLib.py", line 549, in <module>
    class StructuralNode(MBEntity):
  File "/home/shimul/.local/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 202, in __new__
    complete_model_class(
  File "/home/shimul/.local/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 539, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
  File "/home/shimul/.local/lib/python3.10/site-packages/pydantic/main.py", line 626, in __get_pydantic_core_schema__
    return handler(source)
  File "/home/shimul/.local/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(source_type)
  File "/home/shimul/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 502, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/home/shimul/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 753, in _generate_schema_inner
    return self._model_schema(obj)
  File "/home/shimul/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 580, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/home/shimul/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 580, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/home/shimul/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 916, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
  File "/home/shimul/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1081, in _common_field_schema
    schema = self._apply_annotations(
  File "/home/shimul/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1825, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/home/shimul/.local/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(source_type)
  File "/home/shimul/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1806, in inner_handler
    schema = self._generate_schema_inner(obj)
  File "/home/shimul/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 758, in _generate_schema_inner
    return self.match_type(obj)
  File "/home/shimul/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 844, in match_type
    return self._unknown_type_schema(obj)
  File "/home/shimul/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 405, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'MBDynLib.Position'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.7/u/schema-for-unknown-type
```

I figured the `Position` class should also inherit from `MBEntity`, but after adding that I ran into a different error which I can't make sense of.
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/lib/python3.10/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.10/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/usr/lib/python3.10/unittest/main.py", line 158, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
  File "/usr/lib/python3.10/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.10/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.10/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/shimul/Downloads/MyGitHub/MBDyn/contrib/PythonPreprocessor/test_MBDynLib.py", line 4, in <module>
    import MBDynLib as l
  File "/home/shimul/Downloads/MyGitHub/MBDyn/contrib/PythonPreprocessor/MBDynLib.py", line 902, in <module>
    class Clamp(Element):
  File "/home/shimul/Downloads/MyGitHub/MBDyn/contrib/PythonPreprocessor/MBDynLib.py", line 903, in Clamp
    def __init__(self, idx, node, pos = Position('', 'node'), 
  File "/home/shimul/Downloads/MyGitHub/MBDyn/contrib/PythonPreprocessor/MBDynLib.py", line 532, in __init__
    self.reference = ref
  File "/home/shimul/.local/lib/python3.10/site-packages/pydantic/main.py", line 839, in __setattr__
    raise ValueError(f'"{self.__class__.__name__}" object has no field "{name}"')
ValueError: "Position" object has no field "reference"
```

How can a `Position` object not have a `reference` field?

**Comment by Maarrk** [comment]
From the description I understand that the code that causes these errors isn't present in the repository at the moment, so I can't check it myself. In the file I see that `Position` isn't an `MBEntity`:
https://github.com/Shimul-Baidya/MBDyn/blob/83b5bade96c2aaa1026b19bd7d5d39e98064fffe/contrib/PythonPreprocessor/MBDynLib.py#L515

> How can a `Position` object not have a `reference` field?

In current code, the `reference` is only defined inside the `__init__` method. I think for pydantic it needs to be a class attribute, like this:
```python
class Position:
    reference: Any
    relative_position: Any
    
    def __init__(self, ref, rel_pos):
```

You probably need more specific types than `typing.Any`, I'm just showing the syntax

**Comment by Shimul-Baidya** [comment]
I ended up refactoring the `Position` and `Reference` class like [this](https://github.com/Shimul-Baidya/MBDyn/commit/642eda4016f2cfb41d9892e0f0879ca49bc3e06b).

Apparently, I need this for using the `eye` and `null` class. Can I do it in a way so that I don't have to use this config?
https://github.com/Shimul-Baidya/MBDyn/blob/642eda4016f2cfb41d9892e0f0879ca49bc3e06b/contrib/PythonPreprocessor/MBDynLib.py#L537

Please give it a read and suggest changes where necessary.

**Comment by Maarrk** [comment]
The refactor looks good, and I love that I can just look at the tests to see how the class is supposed to be used 👍 

The two arbitrary classes are just wrappers around a constant string value, so we could change them to something that pydantic understands.
https://github.com/Shimul-Baidya/MBDyn/blob/65ba99cce26d12e574dc50dcd9549191e2fa35c3/contrib/PythonPreprocessor/MBDynLib.py#L468-L478

For classes as simple as this, with `__str__` method you can make them inherit `MBEntity`, and it should be enough:
```python
class null(MBEntity):
    def __str__(self):
        return 'null'
```

**Comment by Shimul-Baidya** [comment]
I refactored the null and eye classes in MBDynLib.py to inherit from MBEntity.

Commit Link: [24ac6dd](https://github.com/Shimul-Baidya/MBDyn/commit/24ac6ddcb6f53ada2aa79baad92315b768fdb413)
